# Generated by Django 4.0.4 on 2022-05-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=150, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=150, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Femail', 'Femail')], max_length=6, verbose_name='Gender')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Phone No.')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Mail id')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Applied', max_length=8, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'candidate_detail',
                'verbose_name_plural': 'candidate_details',
                'db_table': 'candidate_details',
                'unique_together': {('email', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_resume', to='portal.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='skill')),
                ('skill_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=12, verbose_name='skill_level')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skill', to='portal.candidate')),
            ],
            options={
                'verbose_name': 'skill_detail',
                'verbose_name_plural': 'skill_details',
                'db_table': 'skills_details',
                'unique_together': {('candidate', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_degree_name', models.CharField(max_length=50, verbose_name='certificate_degree_name')),
                ('major', models.CharField(max_length=50, verbose_name='major')),
                ('institute_name', models.CharField(max_length=50, verbose_name='institute_name')),
                ('starting_date', models.DateField(verbose_name='starting_date')),
                ('completion_date', models.DateField(verbose_name='completion_date')),
                ('percentage', models.SmallIntegerField(verbose_name='percentage')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_education', to='portal.candidate')),
            ],
            options={
                'verbose_name': 'education_detail',
                'verbose_name_plural': 'education_details',
                'db_table': 'education_details',
                'unique_together': {('candidate', 'certificate_degree_name')},
            },
        ),
    ]
